---
- hosts: servers
  gather_facts: yes
  become: yes
  tasks:
    - name: Upadate cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  vars:
    app_path: ./app.py
    app_command: "python {{ app_path }}.py"

  tasks:
    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: latest

    - name: Install Flask
      pip:
        name: flask
        state: latest
    - name: copy app.py
      copy:
        src: "{{ app_path }}"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Running flask app
      shell: "{{ app_command }}"
      async: 3600
      poll: 0     
- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
    - name: Upadate cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  vars:
    haproxy_config_path: /etc/haproxy/haproxy.cfg
    haproxy_template_path: ./haproxy.cfg.j2

  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        state: present
    - name: Copy HAproxy configuration file
      template:
        src: "{{ haproxy_template_path }}"
        dest: "{{ haproxy_config_path }}"
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
