---
- name: Deploy HAProxy and Flask app
  hosts: all
  become: true

  tasks:
    - name: Install HAProxy package
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
      notify:
        - Restart HAProxy

    - name: Deploy Flask app
      copy:
        src: myapp.py
        dest: /opt/myapp/
        mode: 0644

    - name: Install Flask dependencies
      pip:
        name: "{{ item }}"
      with_items:
        - flask
        - gunicorn

    - name: Configure systemd service for Flask app
      template:
        src: myapp.service.j2
        dest: /etc/systemd/system/myapp.service
        mode: 0644
      notify:
        - Reload systemd

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

    - name: Reload systemd
      systemd:
        daemon_reload: yes
        state: reloaded